### ISSUE TITLE
Add option to add one's own set of tips

### ISSUE THREAD

**Issue by rohit-smpx** [hanneskaeufler/danger-plugin-mentor#86]
Some tip's only make sense in a specific repo or org. 
Usage would be something like:
```ts
// dangerfile.js
import mentor from 'danger-plugin-mentor'

mentor({extraTips: [
	{
		text: 'Check out the Wiki for the most common gotchas faced by the team',
		url: '<url to internal wiki page>',
	},
]})
```

Would be even better if we could link to a json file so that a common list can be used across an Org. But that can also be done manually just before calling mentor.

I'll be willing to open a PR if this seems like a good idea.

**Comment by hanneskaeufler** [comment]
That's a great idea. I just took a run at it in PR #87. This will automatically land in a new release once I merge it.

**Comment by hanneskaeufler** [comment]
I also shipped a `fromJson` to help you create a list of tips. You should be able to do

```
mentor([], [...defaultTips, ..fromJson("...")])
```

See Readme for imports and more examples.

**Comment by rohit-smpx** [comment]
Great! Will try it out
